language: python

cache:
      directories:
              - $HOME/.pip-cache/

python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install --cache-dir $HOME/.pip-cache -r requirements_debug.txt

script:
    coverage run --source=. --omit="*/migrations/*" manage.py test

after_success:
    coveralls
