language: python

python:
    - "2.7"

install:
    pip install --use-mirrors -r requirements_debug.txt

script:
    coverage run --source=. --omit="*/migrations/*" manage.py test

after_success:
    coveralls
