sudo: false
language: python

cache:
      directories:
              - $HOME/.pip-cache/

python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install --cache-dir $HOME/.pip-cache -r requirements_debug.txt

script:
    - coverage run --source=. --omit="*/migrations/*" manage.py test
#   - pep8 --exclude="*/migrations/*",".ropeproject/*" --ignore=E501,W292,E265,E266,E402,E126 .

after_success:
    coveralls
